// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeDLpj40Ds-yWorRCKY77pHSDgOaruqlQ',
    appId: '1:515803289777:web:849cc672a09f017931ea90',
    messagingSenderId: '515803289777',
    projectId: 'react-firebase-34d17',
    authDomain: 'react-firebase-34d17.firebaseapp.com',
    storageBucket: 'react-firebase-34d17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeDLpj40Ds-yWorRCKY77pHSDgOaruqlQ',
    appId: '1:515803289777:web:849cc672a09f017931ea90',
    messagingSenderId: '515803289777',
    projectId: 'react-firebase-34d17',
    authDomain: 'react-firebase-34d17.firebaseapp.com',
    storageBucket: 'react-firebase-34d17.appspot.com',
  );
}
